baseurl: "/"
paginate_path: "/page:num"
paginate: 12
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-youtube

url: # Your complete URL https://your.domain.om
sitename: Kochen Mit KI
imglogopath: /assets/images/logo.png
faviconpath: # Path To Favicon
cookiealert: Unsere Seite benutzt Cookies
appletouchiconpath: # Path To Apple-Touch Favicon
author: Kochen Mit KI
htmlheadstart:
htmlbeforeheadend: site-htmlbeforeheadend.html
htmlbodystart:
htmlbeforebodyend: