baseurl: "/"
paginate_path: "/page:num"
paginate: 12
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-youtube

url: # Your complete URL https://your.domain.om
sitename: Speedypreneur
imglogopath: /assets/images/logo.png
faviconpath: # Path To Favicon
cookiealert: Hello
appletouchiconpath: # Path To Apple-Touch Favicon
author: # Will be displayed at every post as the post-author
portionen_icon: <i class="fa-solid fa-pizza-slice"></i>
timer_icon: <i class="fa-solid fa-hourglass-end"></i>
htmlheadstart:
htmlbeforeheadend: site-htmlbeforeheadend.html
htmlbodystart:
htmlbeforebodyend:

